services:
  build_containers:
    build:
      context: .
    container_name: build_containers
    env_file:
      - .env
    volumes:
      - ./:/var/containers
      - /var/run/docker.sock:/var/run/docker.sock
    restart: "no"
